name: Debugging Demo


on:
  workflow_dispatch:


env:
  USER_1: "foo-user"
  USER_2: "bar-user"


jobs:
  debug_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Set USERNAME from USER_1
        run: |
          echo "USERNAME=$USER_1" >> $GITHUB_ENV


      - name: Print USERNAME and Fail
        run: |
          echo "Printing USERNAME from previous step"
          echo "Username: $USERNAME"
          exit 1


      - name: Print USER_2
        run: |
          echo "Printing USER_2: $USER_2"